name: Deploy HTML to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.HOST_DNS }} >> ~/.ssh/known_hosts

      - name: Copy files to EC2
        run: |
          scp -r ./myweb_website.html/* ${{ secrets.USERNAME }}@${{ secrets.HOST_DNS }}:/tmp/site

      - name: Deploy to NGINX root
        run: |
          ssh ${{ secrets.USERNAME }}@${{ secrets.HOST_DNS }} << 'EOF'
          sudo apt update
          sudo apt install nginx -y
            sudo mkdir -p /var/www/html
            sudo cp -r /tmp/site/* /var/www/html/
            sudo systemctl restart nginx
          EOF


